test: main.cpp Simulation.cpp Simulation.h Body.h helper/Vector.h helper/src/Vector.cpp helper/IOManager.h helper/src/IOManager.cpp Constants.h
	g++ -o roche_limit main.cpp Simulation.cpp Simulation.h Body.h helper/Vector.h helper/src/Vector.cpp helper/IOManager.h helper/src/IOManager.cpp Constants.h
