test: main.cpp src/Simulation.cpp include/Simulation.h include/Body.h helper/include/Vector.h helper/src/Vector.cpp helper/include/IOManager.h helper/src/IOManager.cpp include/Constants.h
	g++ -o roche_limit main.cpp src/Simulation.cpp include/Simulation.h include/Body.h helper/include/Vector.h helper/src/Vector.cpp helper/include/IOManager.h helper/src/IOManager.cpp include/Constants.h
